In [3]:
!python –m pip install numpy

python: can't open file 'c:\\Users\\BICH\\OneDrive\\Desktop\\class\\CODE_VD\\C3\\–m': [Errno 2] No such file or directory


In [4]:
!python -m pip install --upgrade pip
!python -m pip install numpy

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   -------------------------------

In [5]:
import numpy as np #np là bí danh (alias) chuẩn được cộng đồng python sử dụng
np.__version__  #kiểm tra version của numpy

'2.3.4'

In [6]:
import numpy as np
#Kiểu dữ liệu nguyên:
arr_int=np.array([1,2,3,4],dtype=np.int32)
arr_int.dtype

dtype('int32')

In [7]:
#Kiểu dữ liệu số thực:
arr_float = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr_float.dtype # Output: float64

dtype('float64')

In [8]:
#Kiểu dữ liệu chuỗi (string):
arr_string = np.array(['apple', 'banana', 'orange'], 
dtype=np.str_)
arr_string.dtype # Output: <U6

dtype('<U6')

In [9]:
#Kiểu dữ liệu logic (boolean):
arr_bool = np.array([True, False, True], dtype=np.bool_)
arr_bool.dtype # Output: bool

dtype('bool')

In [10]:
arr = np.array([1.5, 2.7, 3.2])

arr

array([1.5, 2.7, 3.2])

In [11]:
#kiểm tra dữ liệu của các phần tử arr
arr.dtype

dtype('float64')

In [12]:
#thực hiện chuyển kiểu dữ liệu
arr_int = arr.astype(np.int32)

print(arr_int, arr_int.dtype)

[1 2 3] int32


In [13]:
import numpy as np

#kiểu dữ liệu nguyên
arr_int=np.array([1,2,3,4],dtype=np.int32)
arr_int.dtype

dtype('int32')

In [14]:
#Kiểu dữ liệu số thực:
arr_float = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr_float.dtype # Output: float64

dtype('float64')

In [15]:
#Kiểu dữ liệu chuỗi (string):
arr_string = np.array(['apple', 'banana', 'orange'], 
dtype=np.str_)
arr_string.dtype # Output: <U6

dtype('<U6')

In [16]:
#Kiểu dữ liệu logic (boolean):
arr_bool = np.array([True, False, True], dtype=np.bool_)
arr_bool.dtype # Output: bool

dtype('bool')

In [17]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr_1 = np.array(my_list)
print(arr_1)

[1 2 3 4 5]


In [18]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr_2 = np.array(my_list, dtype=float)
print(arr_2)

[1. 2. 3. 4. 5.]


In [19]:
import numpy as np
my_tuple = (1, 2, 3, 4, 5)
arr_3 = np.array(my_tuple)
print(arr_3)

[1 2 3 4 5]


In [20]:
import numpy as np
arr_4=np.array([(1,2,3), (4,5,6)])
print(arr_4)

[[1 2 3]
 [4 5 6]]


In [21]:
import numpy as np
#Tạo mảng có 5 phần tử là số nguyên nhận giá trị 0
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [22]:
import numpy as np
# Tạo mảng kích thước 3x3 các số thực có giá trị = 1
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
import numpy as np
# Tạo mảng kích thước 5x5 các số thực có giá trị = 100
np.full((5,5),100,dtype=float)

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [24]:
import numpy as np
# Tạo mảng chứa các số từ 0 đến 9
arr_1 =np.arange(10)
print(arr_1)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
import numpy as np
# Tạo mảng chứa các số từ 5 đến 14 với bước nhảy là 2
arr_2 =np.arange(5, 15, 2)
print(arr_2)

[ 5  7  9 11 13]


In [26]:
import numpy as np
# Tạo mảng chứa các số từ 0 đến 1 với bước nhảy là 0.1 và kiểu dữ liệu là float.
arr_3 =np.arange(0, 1, 0.1, dtype=float)
print(arr_3)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [27]:
import numpy as np
# Tạo mảng chứa 5 giá trị từ 0 đến 10 (gồm giá trị kết thúc)
arr_1 = np.linspace(0, 10, 5)
print(arr_1)

[ 0.   2.5  5.   7.5 10. ]


In [28]:
# Tạo mảng chứa 10 giá trị từ 0 đến 1 (không chứa giá trị # kết thúc)
arr_2 = np.linspace(0, 1, 10, endpoint=False)
print(arr_2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [29]:
# Tạo mảng chứa 100 giá trị từ 1 đến 10 và trả về kích thước bước.
arr_3, step = np.linspace(1, 10, 100, retstep=True)
print(arr_3)
print("Step size:", step)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [30]:
import numpy as np
# Tạo môt mảng 1 chiều gồm 5 giá trị ngẫu nhiên từ phân phối đều 
#trong khoảng từ 0 đến 1
arr_5 = np.random.random(5)
print(arr_5)

[0.55379561 0.75754785 0.8307822  0.59085353 0.03091704]


In [31]:
import numpy as np
# Tạo môt mảng 100 giá trị ngẫu nhiên từ phân phối chuẩn với # trung bình 0 và độ lệch chuẩn là 1.
arr_6 = np.random.normal(loc=0.0, scale=1.0, size=100)
print(arr_6)

[-1.54103105e+00 -1.87322337e+00 -3.01470622e-01  2.02859758e+00
 -1.28861067e+00  8.26789182e-01  1.90460147e-01  3.12146933e-01
  1.54465735e-01 -7.22171836e-01 -7.88433614e-01 -1.41097298e+00
 -6.94946332e-01 -1.78925147e+00 -1.58942723e+00  1.05231285e+00
  8.72288311e-02 -2.15355131e+00 -7.50968764e-01  2.22014726e-01
  1.10453417e-01 -2.21599129e+00 -5.73992130e-01  2.37433486e-01
 -4.35263390e-01  2.00740904e+00 -7.82382145e-01  7.79833797e-01
  8.79054151e-01  7.45844408e-01  1.03077640e-01  2.27589152e-01
  4.17180614e-01  7.99079870e-02 -6.59917887e-01  1.87844119e+00
  1.34346348e+00  9.89553265e-01  5.10200642e-02 -1.87033862e+00
 -3.34434662e-01 -1.25755837e-01  3.99826231e-01  4.52847675e-01
 -5.77503256e-01  1.13308081e+00  5.50598206e-01 -2.98256894e-01
  1.18032304e+00  1.84271695e+00  6.60136590e-01 -1.79808992e+00
 -6.92347888e-01  1.44497452e+00  1.25042285e-03  1.77093346e+00
 -8.40858758e-01  1.42759085e+00 -1.85754784e+00 -3.14938268e-01
 -1.15985209e+00  6.88015

In [32]:
import numpy as np
# Tạo mảng 2 chiều 3x3 gồm các số nguyên ngẫu nhiên từ 0 9
arr_7 = np.random.randint(0,10,(3,3))
print(arr_7)

[[7 9 2]
 [6 8 0]
 [4 1 9]]


In [33]:
import numpy as np
# Tạo mảng 2 chiều 3x3 
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
import numpy as np
# Tạo mảng rỗng gồm 5 phần tử, giá trị của 5 phần tử này có thể là bất kỳ giá trị
# nào đã lưu trong bộ nhớ trước đó.
np.empty(5)

array([0.55379561, 0.75754785, 0.8307822 , 0.59085353, 0.03091704])

In [38]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])

print("Số chiều của mảng là:",arr.ndim)
print("Kích thước của mảng là:",arr.shape)
print("Tổng số phần tử trong mảng là:", arr.size)
print("Kiểu dữ liệu của các phần tử trong mảng là:", arr.dtype)
print("Kích thước theo (byte) của mỗi phần tử trong mảng là:", arr.itemsize)
print("Tổng kích thước theo (byte) của mảng là: ", arr.nbytes)

#bổ sung
print("Strides ( bước nhảy bộ nhớ) là:", arr.strides)

#ví dụ
print("Tổng theo trục 0 ( theo cột):", arr.sum(axis=0))
print("Tổng theo trục 1 ( theo cột):", arr.sum(axis=1))

Số chiều của mảng là: 2
Kích thước của mảng là: (2, 3)
Tổng số phần tử trong mảng là: 6
Kiểu dữ liệu của các phần tử trong mảng là: int64
Kích thước theo (byte) của mỗi phần tử trong mảng là: 8
Tổng kích thước theo (byte) của mảng là:  48
Strides ( bước nhảy bộ nhớ) là: (24, 8)
Tổng theo trục 0 ( theo cột): [5 7 9]
Tổng theo trục 1 ( theo cột): [ 6 15]


In [39]:
import numpy as np
arr_a = np.array([[1,2,3,4],
[5,6,7,8],
[9,10,11,12]])
#dùng hàm np.sum() và không có 'axis'
np.sum(arr_a)

np.int64(78)

In [40]:
#Dùng hàm np.sum() với 'axis =0'
np.sum(arr_a,axis=0)

array([15, 18, 21, 24])

In [41]:
#Dùng hàm np.sum với 'axis=1'
np.sum(arr_a, axis=1)

array([10, 26, 42])

In [42]:
import numpy as np
A=np.array([1, 2, 3, 4, 5])
A[0]

np.int64(1)

In [43]:
A[4]

np.int64(5)

In [44]:
A[-1]

np.int64(5)

In [45]:
A[-2]

np.int64(4)

In [46]:
import numpy as np
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B[1,2]

np.int64(6)

In [47]:
B[1,2]

np.int64(6)

In [3]:
import numpy as np
A=np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import numpy as np
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [5]:
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print("Cột đầu tiên của mảng arr là: ",arr[:,0]) 
print("Hàng đầu tiên của mảng arr là:",arr[0,:])
print("Hàng đầu tiên của mảng arr là:",arr[0])

Cột đầu tiên của mảng arr là:  [1 4 7]
Hàng đầu tiên của mảng arr là: [1 2 3]
Hàng đầu tiên của mảng arr là: [1 2 3]


In [7]:
import numpy as np
# Tạo mảng 2 chiều 3x3
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Lấy view mới chỉ chứa 2 dòng và 2 cột của mảng gốc
arr_view = arr_2d[:2, :2].view()
print(arr_view)

[[1 2]
 [4 5]]


In [9]:
arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 10.
print(arr_view)
print("Mảng gốc sau khi thay đổi giá trị trong view:")
print(arr_2d)

[[100   2]
 [  4   5]]
Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [10]:
type(arr_view)

numpy.ndarray

In [12]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array_copy = arr_2d[:2, :2].copy()
print(sub_array_copy)

[[1 2]
 [4 5]]


In [14]:
arr=np.arange(1,10)
print(f'Mảng 1 chiều ban đầu: \n',arr)
grid= arr.reshape((3,3))

print(f'Mảng 2 chiều sau khi reshape: \n',arr)

Mảng 1 chiều ban đầu: 
 [1 2 3 4 5 6 7 8 9]
Mảng 2 chiều sau khi reshape: 
 [1 2 3 4 5 6 7 8 9]


In [15]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [16]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [17]:
np.newaxis is None

True

In [18]:
y=x[np.newaxis, :]
print(f'ma trận x ban đầu:',x)
print(f'ma trận y sau khi thêm hàng:',y)

ma trận x ban đầu: [1 2 3]
ma trận y sau khi thêm hàng: [[1 2 3]]


In [19]:
z=x[:,np.newaxis]
print(f'ma trận x ban đầu:',x)
print('ma trận z sau khi thêm cột:\n',z)

ma trận x ban đầu: [1 2 3]
ma trận z sau khi thêm cột:
 [[1]
 [2]
 [3]]


In [20]:
#giả sử x có shape(3,) ->1 chiều,
x

array([1, 2, 3])

In [21]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [22]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [23]:
np.ndim(x)

1

In [24]:
np.ndim(x.reshape((3, 1)))

2

In [25]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate([x,y], axis=1) #lỗi vì mảng x và y là mảng 1 chiều, k có trục 1 để nối theo cột

AxisError: axis 1 is out of bounds for array of dimension 1

In [27]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
np.concatenate((a, b)) 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
a = np.array([[1, 2],
              [3, 4]])
b=np.array([[5, 6],
            [7, 8]])
c=np.vstack((a,b)) # ghép mảng a và b theo hàng ( trục axis=0) để tạo mảng mới 4x2
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
d = np.hstack((a,b))
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [31]:
import numpy as np
arr = np.arange(10) #Tạo mảng arr gồm 10 phần tử từ 0-9
sub_arr1=np.split(arr,[3, 6])
print("Mảng con sub_arr1 là:", sub_arr1, "\n")

Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 



In [32]:
sub_arr2=np.split(arr,2)
print("Mảng con sub_arr2 là:", sub_arr2)

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [33]:
import numpy as np
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
upper,lower = np.vsplit(arr,2) 
print("phần trên của mảng sau khi vsplit:\n",upper)
print("phần dưới của mảng sau khi vsplit:\n",lower)

phần trên của mảng sau khi vsplit:
 [[0 1 2 3]
 [4 5 6 7]]
phần dưới của mảng sau khi vsplit:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [35]:
left,right = np.hsplit(arr, 2)
print("phần bên trái của mảng sau khi hsplit:\n",left)
print("phần bên phải của mảng sau khi hsplit:\n",right)

phần bên trái của mảng sau khi hsplit:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
phần bên phải của mảng sau khi hsplit:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [36]:
import numpy as np
arr=np.array([1,2,3])
new_arr=np.append(arr,4)
print(arr)
print(new_arr)

[1 2 3]
[1 2 3 4]


In [38]:
arr = np.array([1, 2, 3, 4, 5])
new_element = 10
index_to_insert = 2
new_arr = np.insert(arr, index_to_insert, new_element)
print(new_arr)

[ 1  2 10  3  4  5]


In [39]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
new_element = [7, 8]
row_to_insert = 1
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0)
print(new_arr_2d)

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


In [40]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr==3)
indices

(array([2]),)

In [41]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.argwhere(arr==3)
indices

array([[2]])

In [42]:
arr = np.array([1, 5, 2, 3, 4])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print(max_idx)
print(min_idx)

1
0


In [43]:
arr = np.array([1, 2, 3, 4, 5])
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

In [45]:
arr

array([1, 2, 3, 4, 5])

In [46]:
arr.sort()
print(arr)

[1 2 3 4 5]


In [44]:
arr = np.array([1, 2, 3, 4, 5])
arr.sort()
arr

array([1, 2, 3, 4, 5])

In [47]:
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]
sorted_arr_descending

array([5, 4, 3, 2, 1])

In [48]:
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = 2 #Xóa phần tử 4 ở chỉ mục 2.
new_arr=np.delete(arr,idx_to_delete)
new_arr

array([3, 1, 2, 5])

In [49]:
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = [1, 3]
new_arr = np.delete(arr, idx_to_delete)
new_arr

array([3, 4, 5])

In [52]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_idx_to_delete = 1
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)

print(f'mảng 2D ban đầu: \n',arr_2d)
print(f'mảng 2D sau khi xóa dòng {row_idx_to_delete}: \n',new_arr_2d)

mảng 2D ban đầu: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
mảng 2D sau khi xóa dòng 1: 
 [[1 2 3]
 [7 8 9]]


In [53]:
arr = np.array([1, 2, 3, 4, 5])
del arr
arr

NameError: name 'arr' is not defined

In [54]:
arr = np.array([1, 2, 3, 4, 5])
arr = None
print(arr)

None


In [55]:
dtype = [('name', 'U20'), ('age', int), ('height', float)]

In [58]:
age = [22, 40, 31, 18, 50]
height = [181.3, 160.6, 163.2, 175.5, 165.0]

In [60]:
data = np.array([('Minh', 22, 181.3),
('Lan', 40, 160.6),
('Linh', 31, 163.2),
('Lương',18,175.5),
('Thanh',50, 165.0)], dtype=dtype)
print(f'structured: \n',data)

structured: 
 [('Minh', 22, 181.3) ('Lan', 40, 160.6) ('Linh', 31, 163.2)
 ('Lương', 18, 175.5) ('Thanh', 50, 165. )]


In [59]:
print(data)
print(data.dtype)

[('Minh', 22, 181.3) ('Lan', 40, 160.6) ('Linh', 31, 163.2)
 ('Lương', 18, 175.5) ('Thanh', 50, 165. )]
[('name', '<U20'), ('age', '<i8'), ('height', '<f8')]


In [61]:
import numpy as np
dtype = [('name', 'U20'), ('age', int), ('height', float)]
data = np.array([('Minh', 22, 165.5),
                 ('Lan', 40, 160.0),
                 ('Linh', 31, 165.0),
                 ('Lương',18,166.5),
                 ('Thanh',50, 170.0)], dtype=dtype)
rec_data = data.view(np.recarray)
print(rec_data.name)
print(rec_data.age)
print(rec_data.height)


['Minh' 'Lan' 'Linh' 'Lương' 'Thanh']
[22 40 31 18 50]
[165.5 160.  165.  166.5 170. ]


In [63]:
import numpy as np
import time
arr = np.arange(100000000, dtype=np.int64)
start_time = time.time()
total = np.int64(0)
for num in arr:
    total += num
end_time = time.time()
elapsed_time_loop = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total)
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop)
start_time = time.time()
total = np.sum(arr)
end_time = time.time()
elapsed_time_npsum = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total)
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum)
num_times_faster = elapsed_time_loop / elapsed_time_npsum
print("Sử dụng vòng lặp chậm hơn: ~",int(num_times_faster),"lần")

Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 17.44969916343689
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.09838414192199707
Sử dụng vòng lặp chậm hơn: ~ 177 lần


In [64]:
import numpy as np
import timeit 
#tính tổng các mảng sd numpy
np_setup = "import numpy as np; np_array = np.arange(1, 1000001)"
np_code = "np_sum = np.sum(np_array)"
np_time = timeit.timeit(stmt=np_code, setup=np_setup, number=10)
#tính tổng của danh sách sử dụng list
list_setup = "list_array = list(range(1, 1000001))"
list_code = "list_sum = sum(list_array)"
list_time = timeit.timeit(stmt=list_code, setup=list_setup, 
number=10)
print("Thời gian tính toán của Numpy:", np_time)
print("Thời gian tính toán của List:", list_time)
print("Numpy tính nhanh hơn List ở lượt chạy là ~ ", int(list_time/np_time), "lần!!")

Thời gian tính toán của Numpy: 0.013083100086078048
Thời gian tính toán của List: 0.31560839992016554
Numpy tính nhanh hơn List ở lượt chạy là ~  24 lần!!


In [65]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
Tong = np.add(arr1,arr2)
Hieu = np.subtract(arr1,arr2)
Tich = np.multiply(arr1,arr2)
Thuong = np.divide(arr1,arr2)
print("Tổng của arr1 + arr2 là:",Tong)
print("Hiệu của arr1 - arr2 là:",Hieu)
print("Tích của arr1 * arr2 là:",Tich)
print("Thương của arr1/arr2 là:",Thuong)

Tổng của arr1 + arr2 là: [5 7 9]
Hiệu của arr1 - arr2 là: [-3 -3 -3]
Tích của arr1 * arr2 là: [ 4 10 18]
Thương của arr1/arr2 là: [0.25 0.4  0.5 ]


In [66]:
import numpy as np
arr1=np.random.rand(5)
arr1

array([0.83154364, 0.52039618, 0.59694652, 0.12645392, 0.51771315])

In [67]:
arr2=np.random.rand(5)
arr2

array([0.94005378, 0.16087994, 0.6098718 , 0.52571556, 0.95866167])

In [68]:
arr_maximum=np.maximum(arr1,arr2)
print("Mảng kết quả là:",arr_maximum)

Mảng kết quả là: [0.94005378 0.52039618 0.6098718  0.52571556 0.95866167]


In [69]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Căn bậc hai của các phần tử trong mảng
kq_can_hai = np.sqrt(arr) 
# Lũy thừa 2 của các phần tử trong mảng
kq_luy_thua_2 = np.power(arr, 2)
# Logarit tự nhiên (cơ số e) của các phần tử trong mảng
kq_logarit = np.log(arr)
# Giá trị tuyệt đối của các phần tử trong mảng
kq_tri_tuyet_doi = np.abs(arr)
# Hàm logic NOT (đảo ngược giá trị) của các phần tử trong mảng
kq_not_logic = np.logical_not(arr)
#Hàm sin của các phần tử trong mảng
kq_sin=np.sin(arr)
print("Căn bậc hai của từng phần tử trong mảng là: ", kq_can_hai) 
print("Lũy thừa bậc hai của từng phần tử trong mảng là: ", kq_luy_thua_2)
print("Logarit của từng phần tử trong mảng là: ", kq_logarit) 
print("Trị tuyệt đối của từng phần tử trong mảng là: ", kq_tri_tuyet_doi) 
print("Kết quả đảo ngược giá trị của các phần tử trong mảng là:", kq_not_logic)
print("Kết quả hàm sin của các phần tử trong mảng là:", kq_sin)

Căn bậc hai của từng phần tử trong mảng là:  [1.         1.41421356 1.73205081 2.         2.23606798]
Lũy thừa bậc hai của từng phần tử trong mảng là:  [ 1  4  9 16 25]
Logarit của từng phần tử trong mảng là:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Trị tuyệt đối của từng phần tử trong mảng là:  [1 2 3 4 5]
Kết quả đảo ngược giá trị của các phần tử trong mảng là: [False False False False False]
Kết quả hàm sin của các phần tử trong mảng là: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [70]:
import numpy as np
arr1 = np.array([0,1,2])
arr2 = np.array([5,5,5])
arr1 + arr2

array([5, 6, 7])

In [71]:
import numpy as np
arr1 = np.array([0,1,2])
arr1 + 5

array([5, 6, 7])

In [72]:
import numpy as np
arr = np.array([0,1,2])
arr

array([0, 1, 2])

In [73]:
M=np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
arr + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [75]:
import numpy as np
arr1 = np.arange(3)
arr2=np.arange(3)[:,np.newaxis]
print(arr1)
print(arr2)

[0 1 2]
[[0]
 [1]
 [2]]


In [76]:
arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [77]:
import numpy as np
arr1=np.ones((2,3))
arr2 = np.arange(3)
print(arr1.shape)
print(arr2.shape)

(2, 3)
(3,)


In [78]:
arr1+arr2

array([[1., 2., 3.],
       [1., 2., 3.]])

In [79]:
arr1 = np.ones((2,3))
arr2 = np.arange(3)


In [80]:
print(arr1.shape)
print(arr2.shape)

(2, 3)
(3,)


In [81]:
arr1+arr2

array([[1., 2., 3.],
       [1., 2., 3.]])

In [83]:
import numpy as np
data = np.random.randint(100, 200, size=1000)
mean_value = np.array([data.mean()])
percentage_growth=(data - mean_value) / mean_value * 100
print("Dữ liệu gốc:", data[:10])
print("Tỷ lệ phần trăm tăng trưởng:", percentage_growth[:10])

Dữ liệu gốc: [157 118 193 173 120 172 105 100 149 128]
Tỷ lệ phần trăm tăng trưởng: [  5.0427196  -21.05069482  29.1289483   15.74771014 -19.712571
  15.07864823 -29.74849963 -33.09380917  -0.30977566 -14.36007574]


In [84]:
import numpy as np
#Mảng đích để lưu trữ kết quả
output=np.zeros((3,3))
#Mảng nguồn arr1, arr2
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
#Thực hiện phép cộng và lưu trữ kết quả vào mảng đích output
np.add(arr1,arr2, out=output)
#In kết quả
print(output)

[[5. 7. 9.]
 [5. 7. 9.]
 [5. 7. 9.]]


In [85]:
import numpy as np
visitors = np.array([10200, 9875, 13567,7900,11200, 8871, 12567])

In [86]:
sum = 0
for i in visitors:
    if (i>10000):
        sum+=i
print(sum)

47534


In [87]:
mask = visitors > 10000
mask

array([ True, False,  True, False,  True, False,  True])

In [88]:
visitors[mask]

array([10200, 13567, 11200, 12567])

In [89]:
visitors[mask].sum()

np.int64(47534)

In [90]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result1 = arr1 > arr2 # Lớn hơn
result2 = arr1 == arr2 # Bằng nhau
result3 = arr1 <= arr2 # Nhỏ hơn hoặc bằng
print("Kết quả lớn hơn:", result1) 
print("Kết quả bằng nhau:", result2) 
print("Kết quả nhỏ hơn hoặc bằng:", result3)

Kết quả lớn hơn: [False False False  True  True]
Kết quả bằng nhau: [False False  True False False]
Kết quả nhỏ hơn hoặc bằng: [ True  True  True False False]


In [91]:
import numpy as np
arr = np.array([[1,0,3],
 [0,5,0],
 [7,0,9]])
count = np.count_nonzero(arr)
count

np.int64(5)

In [92]:
import numpy as np
diemTB = np.array([6.7, 8, 4, 5.8, 9, 8.3, 5, 7.2, 5.5])

In [93]:
diemTB = np.array([6.7, 8, 4, 5.8, 9, 8.3, 5, 7.2, 5.5])
boolArr=(diemTB >= 8) & (diemTB <= 10)
boolArr

array([False,  True, False, False,  True,  True, False, False, False])

In [94]:
np.count_nonzero(boolArr)

np.int64(3)

In [95]:
np.count_nonzero((diemTB >= 8) & (diemTB <= 10) )

np.int64(3)

In [96]:
np.sum(boolArr)

np.int64(3)

In [97]:
import numpy as np
arr = np.array([[1,0,3],
 [0,5,0],
 [7,0,9]])
#Sử dụng phương thức sum kèm theo tham số axis (trục) tương ứng
print("Số phần tử khác 0 theo mỗi hàng:",np.sum(arr !=0, axis=1))
print("Số phần tử khác 0 theo mỗi cột:",np.sum(arr!=0, axis=0))

Số phần tử khác 0 theo mỗi hàng: [2 1 2]
Số phần tử khác 0 theo mỗi cột: [2 1 2]


In [98]:
print("Trong mảng arr có phần tử > 5: ", np.any(arr > 5))
print("Trong mảng arr có phần tử < 0: ", np.any(arr < 0))
print("Trong mảng arr tất cả các phần tử đều < 10: ", np.all(arr < 10))
print("Trong mảng arr tất cả các phần tử đều = 3:", np.all(arr == 3))

Trong mảng arr có phần tử > 5:  True
Trong mảng arr có phần tử < 0:  False
Trong mảng arr tất cả các phần tử đều < 10:  True
Trong mảng arr tất cả các phần tử đều = 3: False


In [99]:
print("Kiểm tra từng cột trong mảng arr, \ncột nào có tất cả các phần tử lớn hơn 1: \n", 
np.all(arr > 1, axis=0))

Kiểm tra từng cột trong mảng arr, 
cột nào có tất cả các phần tử lớn hơn 1: 
 [False False False]


In [100]:
import numpy as np
import numpy.ma as ma
#Tạo một mảng NumPy bình thường
arr = np.array([1,2,3,4,5,6,7,8,9])
# Tạo một mảng mask cho các giá trị không hợp lệ
mask =arr>6
masked_arr=np.ma.masked_array(arr,mask)
masked_arr

masked_array(data=[1, 2, 3, 4, 5, 6, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True],
       fill_value=999999)

In [101]:
valid_values = arr[~mask]
print("Dữ liệu ban đầu:", arr)
print("Mảng mask:", mask)
print("Các giá trị hợp lệ từ mảng ban đầu:", valid_values)

Dữ liệu ban đầu: [1 2 3 4 5 6 7 8 9]
Mảng mask: [False False False False False False  True  True  True]
Các giá trị hợp lệ từ mảng ban đầu: [1 2 3 4 5 6]


In [102]:
import numpy as np
import numpy.ma as ma
#Tạo một mảng NumPy bình thường
arr = np.array([1,2,3,4,5,6,7,8,9])
# Tạo một mảng mask cho các giá trị không hợp lệ
mask =arr>6
masked_arr=np.ma.masked_array(arr,mask,fill_value=100)
print("Masked Array chưa được điền: ", masked_arr)
print("Masked Array đã điền: ", masked_arr.filled())

Masked Array chưa được điền:  [1 2 3 4 5 6 -- -- --]
Masked Array đã điền:  [  1   2   3   4   5   6 100 100 100]


In [103]:
arr = np.array([1,2,3,4,5,6,7,8,9])
#loại các giá trị nhỏ hơn 5
masked_arr1=np.ma.masked_less(arr,5)
print("masked_arr1 :",masked_arr1)
#loại các giá trị nhỏ hơn hoặc bằng 5
masked_arr2=np.ma.masked_less_equal(arr,5)
print("masked_arr1 :", masked_arr2)

masked_arr1 : [-- -- -- -- 5 6 7 8 9]
masked_arr1 : [-- -- -- -- -- 6 7 8 9]


In [104]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
#Truy xuất các phần tử bằng một danh sách các chỉ mục
indices = [1, 3, 4]
sub_arr_1 = arr[indices]
print(sub_arr_1)

[20 40 50]


In [105]:
#Fancy indexing và boolean
sub_arr_boolean = arr[arr > 50]
print("Orignial Array:\n",arr)
# Boolean Indexing
print("After Boolean Condition:",arr[arr>50])

Orignial Array:
 [10 20 30 40 50 60 70 80 90]
After Boolean Condition: [60 70 80 90]


In [106]:
#Mảng chỉ mục là mảng 2 chiều
idx_arr=np.array([[1,2],
[5,6]])
sub_arr_2=arr[idx_arr]
print(sub_arr_2)

[[20 30]
 [60 70]]


In [108]:
arr = np.arange(16).reshape(4, 4)
print("Mảng gốc ban đầu:\n arr = \n", arr)
#Lấy các phần tử arr[3, 1], arr[3, 2] và arr[3, 3] 
sub_arr = arr[3, [1, 2, 3]]
print("Mảng con: sub_arr = ", sub_arr)

Mảng gốc ban đầu:
 arr = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Mảng con: sub_arr =  [13 14 15]


In [109]:
sub_arr = arr[1:, [1, 2, 3]]
print("Mảng con sub_arr:\n", sub_arr)

Mảng con sub_arr:
 [[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [110]:
#Fancy Indexing và masks
arr=np.array([[1,2,3],
[4,5,6],
[7,8,9]])
masks=arr[0,:]%2 == 0 #Lấy hàng 0, chia các phần tử tương ứng 1,2,3 cho 2, 
print("masks:",masks) #Kết quả là mảng [Flase True False]
sub_arr=arr[:,masks] # Kết hợp Fancy indexing và mask, dấu ':' ở vị trí hàng
 # cho biết lấy toàn bộ các hàng của mảng, 
 # chỉ mục cột là masks, chỉ có 1 phần tử True ở vị trí 1
 # Vì vậy chỉ lấy cột có chỉ mục 1, tức cột 1
print("Mảng con mới: \n", sub_arr)

masks: [False  True False]
Mảng con mới: 
 [[2]
 [5]
 [8]]


In [3]:
import pandas as pd
pd.__version__


'2.3.3'

In [4]:
import pandas as pd
data = pd.Series([1.0, 0.25, 6.0, 0.75])
data

0    1.00
1    0.25
2    6.00
3    0.75
dtype: float64

In [6]:
data.values


array([1.  , 0.25, 6.  , 0.75])

In [7]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
data[2]

np.float64(6.0)

In [9]:
import pandas as pd
population_dict = {'Hà Nội':8330830,
 'Quảng Ninh':1358085,
 'Nam Định': 1836270,
 'Đà Nẵng':1195490,
 'TP.Hồ Chí Minh':9411805}
population = pd.Series(population_dict)
population

Hà Nội            8330830
Quảng Ninh        1358085
Nam Định          1836270
Đà Nẵng           1195490
TP.Hồ Chí Minh    9411805
dtype: int64

In [10]:
population['Hà Nội']

np.int64(8330830)

In [11]:
area_dict={'Hà Nội':3358.9,
'Quảng Ninh':6177.7,
'Nam Định':1668.0,
'Đà Nẵng':1284.9,
'TP.Hồ Chí Minh':2061.0}
area = pd.Series(area_dict)
area

Hà Nội            3358.9
Quảng Ninh        6177.7
Nam Định          1668.0
Đà Nẵng           1284.9
TP.Hồ Chí Minh    2061.0
dtype: float64

In [12]:
VietNam = pd.DataFrame({'Dân số':population, 'Diện tích':area})
VietNam

Dân số  Diện tích
Hà Nội          8330830     3358.9
Quảng Ninh      1358085     6177.7
Nam Định        1836270     1668.0
Đà Nẵng         1195490     1284.9
TP.Hồ Chí Minh  9411805     2061.0

In [13]:
VietNam.index

Index(['Hà Nội', 'Quảng Ninh', 'Nam Định', 'Đà Nẵng', 'TP.Hồ Chí Minh'], dtype='object')

In [14]:
VietNam.columns

Index(['Dân số', 'Diện tích'], dtype='object')

In [15]:
VietNam['Dân số']

Hà Nội            8330830
Quảng Ninh        1358085
Nam Định          1836270
Đà Nẵng           1195490
TP.Hồ Chí Minh    9411805
Name: Dân số, dtype: int64

In [16]:
print('Dân số thủ đô Hà Nội:',VietNam['Dân số']['Hà Nội'])
print('Dấn số thủ đô Hà Nội:',VietNam['Dân số'][0])

Dân số thủ đô Hà Nội: 8330830
Dấn số thủ đô Hà Nội: 8330830


C:\Users\BICH\AppData\Local\Temp\ipykernel_1524\2949534939.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print('Dấn số thủ đô Hà Nội:',VietNam['Dân số'][0])


In [17]:
pd.DataFrame(population, columns=['Dân số'])

Dân số
Hà Nội          8330830
Quảng Ninh      1358085
Nam Định        1836270
Đà Nẵng         1195490
TP.Hồ Chí Minh  9411805

In [18]:
data = [{'a':i,'b':2*i}
        for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [19]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [20]:
pd.DataFrame([{'a':1,'b':2},{'b':3,'c': 'KHDL'}])

a  b     c
0  1.0  2   NaN
1  NaN  3  KHDL

In [31]:
import pandas as pd
indA=pd.Index([0, 2, 4, 6, 8])
indB=pd.Index([1, 3, 7, 8, 9])
print('Index A: ', indA)
print('Index B: ', indB)
print('Hợp: ', indA.union(indB)) #hợp (union)
print('Hiệu: ', indA.difference(indB)) #hiệu
print('Giao: ', indA.intersection(indB)) #Giao
print('Hiệu đối xứng: ',indA.symmetric_difference(indB))#hiệu đối xứng
print('A <= B and A!=B: ', indA.isin(indB))

Index A:  Index([0, 2, 4, 6, 8], dtype='int64')
Index B:  Index([1, 3, 7, 8, 9], dtype='int64')
Hợp:  Index([0, 1, 2, 3, 4, 6, 7, 8, 9], dtype='int64')
Hiệu:  Index([0, 2, 4, 6], dtype='int64')
Giao:  Index([8], dtype='int64')
Hiệu đối xứng:  Index([0, 1, 2, 3, 4, 6, 7, 9], dtype='int64')
A <= B and A!=B:  [False False False False  True]


In [35]:
import pandas as pd
tinh = ['Hà Nội', 'Hà Nội', 'Đà Nẵng', 'Đà Nẵng']
nam = [2023, 2024, 2023, 2024]
idx = pd.MultiIndex.from_arrays([tinh, nam], names=['Tỉnh/TP', 'năm'])
df = pd.DataFrame({
    'Dân số':[8330830, 8410000, 1191381, 1210000],
    'Diện tích':[3358.9, 3358.0, 1284.9, 1284.9]
}, index=idx)
print(df)
print('\nTruy cập (Hà Nội, 2024):')
print(df.loc[('Hà Nội', 2024), 'Dân số'])
print('\nMoi năm của Đà Nẵng:')
print(df.loc[('Đà Nẵng', slice(None)), :])

               Dân số  Diện tích
Tỉnh/TP năm                     
Hà Nội  2023  8330830     3358.9
        2024  8410000     3358.0
Đà Nẵng 2023  1191381     1284.9
        2024  1210000     1284.9

Truy cập (Hà Nội, 2024):
8410000

Moi năm của Đà Nẵng:
               Dân số  Diện tích
Tỉnh/TP năm                     
Đà Nẵng 2023  1191381     1284.9
        2024  1210000     1284.9


In [36]:
import pandas as pd
data = pd.Series([1, 2, 3, 4],
 index=['a','b','c','d'])
data

a    1
b    2
c    3
d    4
dtype: int64

In [37]:
'a' in data

True

In [38]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [39]:
data.values

array([1, 2, 3, 4])

In [40]:
list(data.items())

[('a', 1), ('b', 2), ('c', 3), ('d', 4)]

In [41]:
data['e']=9.99

In [42]:
data['a':'c']

a    1.0
b    2.0
c    3.0
dtype: float64

In [43]:
data[0:2]

a    1.0
b    2.0
dtype: float64

In [44]:
mask=(data>1)&(data<4)
mask

a    False
b     True
c     True
d    False
e    False
dtype: bool

In [45]:
data[mask]

b    2.0
c    3.0
dtype: float64

In [46]:
indices_1=['b','d'] #explicit index
selection_1=data[indices_1]
selection_1

b    2.0
d    4.0
dtype: float64

In [47]:
indices_2=[1,3] #implicit index
selection_2=data[indices_2]
selection_2

C:\Users\BICH\AppData\Local\Temp\ipykernel_1524\1501175111.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  selection_2=data[indices_2]


b    2.0
d    4.0
dtype: float64

In [48]:
import pandas as pd
data = pd.Series(['a','b','c','d','e'],index=[1,3,5,6,7])
data

1    a
3    b
5    c
6    d
7    e
dtype: object

In [49]:
data[1]

'a'

In [50]:
data[1:3]

3    b
5    c
dtype: object

In [51]:
import pandas as pd
data=pd.Series(['a','b','c','d','e'],index=[1,3,5,6,7])
data.loc[1]

'a'

In [52]:
data.loc[1:4]

1    a
3    b
dtype: object

In [53]:
data.iloc[1]

'b'

In [54]:
data.iloc[1:4]

3    b
5    c
6    d
dtype: object

In [55]:
import pandas as pd
population = pd.Series({'Hà Nội':8330830,
 'Quảng Ninh':1358490,
 'Nam Định': 1771000,
 'Đà Nẵng':1191381,
 'TP.Hồ Chí Minh':9411805})
area=pd.Series({'Hà Nội':3358.9,
 'Quảng Ninh':6177.7,
 'Nam Định': 1668.0,
 'Đà Nẵng':1284.9,
 'TP.Hồ Chí Minh':2061.0})
data = pd.DataFrame({'Dân số':population, 'Diện tích':area})
data

Dân số  Diện tích
Hà Nội          8330830     3358.9
Quảng Ninh      1358490     6177.7
Nam Định        1771000     1668.0
Đà Nẵng         1191381     1284.9
TP.Hồ Chí Minh  9411805     2061.0

In [56]:
data['Dân số']

Hà Nội            8330830
Quảng Ninh        1358490
Nam Định          1771000
Đà Nẵng           1191381
TP.Hồ Chí Minh    9411805
Name: Dân số, dtype: int64

In [57]:
data['population'] = data['Dân số'] 
print(data)

                 Dân số  Diện tích  population
Hà Nội          8330830     3358.9     8330830
Quảng Ninh      1358490     6177.7     1358490
Nam Định        1771000     1668.0     1771000
Đà Nẵng         1191381     1284.9     1191381
TP.Hồ Chí Minh  9411805     2061.0     9411805


In [58]:
data.population

Hà Nội            8330830
Quảng Ninh        1358490
Nam Định          1771000
Đà Nẵng           1191381
TP.Hồ Chí Minh    9411805
Name: population, dtype: int64

In [59]:
data['Mật độ']=data['Dân số']/data['Diện tích']
data

Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   219.902229
Nam Định        1771000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573

In [60]:
arr_data = data.values # Lấy mảng dữ liệu gốc từ DataFrame
print(arr_data)

[[8.33083000e+06 3.35890000e+03 8.33083000e+06 2.48022567e+03]
 [1.35849000e+06 6.17770000e+03 1.35849000e+06 2.19902229e+02]
 [1.77100000e+06 1.66800000e+03 1.77100000e+06 1.06175060e+03]
 [1.19138100e+06 1.28490000e+03 1.19138100e+06 9.27216904e+02]
 [9.41180500e+06 2.06100000e+03 9.41180500e+06 4.56662057e+03]]


In [61]:
data.T

Hà Nội    Quảng Ninh      Nam Định       Đà Nẵng  \
Dân số      8.330830e+06  1.358490e+06  1.771000e+06  1.191381e+06   
Diện tích   3.358900e+03  6.177700e+03  1.668000e+03  1.284900e+03   
population  8.330830e+06  1.358490e+06  1.771000e+06  1.191381e+06   
Mật độ      2.480226e+03  2.199022e+02  1.061751e+03  9.272169e+02   

            TP.Hồ Chí Minh  
Dân số        9.411805e+06  
Diện tích     2.061000e+03  
population    9.411805e+06  
Mật độ        4.566621e+03

In [62]:
print("Cách 1, sử dụng chuyển vị:", data.T.values[1])
print("Cách 2, sử dụng chỉ mục(index): ", data['Diện tích'].values)

Cách 1, sử dụng chuyển vị: [3358.9 6177.7 1668.  1284.9 2061. ]
Cách 2, sử dụng chỉ mục(index):  [3358.9 6177.7 1668.  1284.9 2061. ]


In [ ]:
#Sử dụng loc
print(data)

print('\n Dữ liệu của Hà Nội:\n',data.loc['Hà Nội'])

print("\n Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:\n",data.loc[:'Nam Định'])

print("\nDữ liệu dân số, diện tích của Hà Nội, Quảng Ninh:\n",data.loc[:'Quảng Ninh',:'Diện tích'])

print("\n Mật độ dân số các Tỉnh/Thành phố:\n",data.loc[:,'Mật độ'])

                 Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   219.902229
Nam Định        1771000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573

 Dữ liệu của Hà Nội:
 Dân số        8.330830e+06
Diện tích     3.358900e+03
population    8.330830e+06
Mật độ        2.480226e+03
Name: Hà Nội, dtype: float64

 Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:
              Dân số  Diện tích  population       Mật độ
Hà Nội      8330830     3358.9     8330830  2480.225669
Quảng Ninh  1358490     6177.7     1358490   219.902229
Nam Định    1771000     1668.0     1771000  1061.750600

Dữ liệu dân số, diện tích của Hà Nội, Quảng Ninh:
              Dân số  Diện tích
Hà Nội      8330830     3358.9
Quảng Ninh  1358490     6177.7

 Mật độ dân số các Tỉnh/Thành phố:
 Hà Nội            2480.2256

In [67]:
print(data)

print("\nDữ liệu của thủ đô Hà Nội:\n",data.iloc[0])

print("\nDữ liệu của Hà Nội, Quảng Ninh và Nam Định:\n",data.iloc[0:3])

print("\nDữ liệu dân số và diện tích của Hà Nội và Quảng Ninh:\n",data.iloc[:2,:2])

print("Mật độ dân số của các tỉnh/thành phố:\n",data.iloc[:,-1])

                 Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   219.902229
Nam Định        1771000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573

Dữ liệu của thủ đô Hà Nội:
 Dân số        8.330830e+06
Diện tích     3.358900e+03
population    8.330830e+06
Mật độ        2.480226e+03
Name: Hà Nội, dtype: float64

Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:
              Dân số  Diện tích  population       Mật độ
Hà Nội      8330830     3358.9     8330830  2480.225669
Quảng Ninh  1358490     6177.7     1358490   219.902229
Nam Định    1771000     1668.0     1771000  1061.750600

Dữ liệu dân số và diện tích của Hà Nội và Quảng Ninh:
              Dân số  Diện tích
Hà Nội      8330830     3358.9
Quảng Ninh  1358490     6177.7
Mật độ dân số của các tỉnh/thành phố:
 Hà Nội          

In [68]:
print(data.loc[data['Diện tích'] > 2000, ['Dân số', 'Mật độ']])

                 Dân số       Mật độ
Hà Nội          8330830  2480.225669
Quảng Ninh      1358490   219.902229
TP.Hồ Chí Minh  9411805  4566.620573


In [70]:
print("Diện tích các tỉnh/TP có mật độ<1000 và dân số>1 triệu:\n",data.loc[(data['Mật độ']<1000) & (data['Dân số']>1000), ['Diện tích','Mật độ']])


Diện tích các tỉnh/TP có mật độ<1000 và dân số>1 triệu:
             Diện tích      Mật độ
Quảng Ninh     6177.7  219.902229
Đà Nẵng        1284.9  927.216904


In [73]:
data.iloc[2,0]=1880000
data

Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   250.000000
Nam Định        1880000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573

In [75]:
data.loc['Quảng Ninh','Mật độ']=250
print("Dữ liệu tỉnh Quảng Ninh được cập nhật:\n", data.loc['Quảng Ninh'])

Dữ liệu tỉnh Quảng Ninh được cập nhật:
 Dân số        1358490.0
Diện tích        6177.7
population    1358490.0
Mật độ            250.0
Name: Quảng Ninh, dtype: float64


In [3]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(100)
arr1 = rng.randint(0, 10, 4)

arr2 = rng.randint(0, 10, (3, 4))

In [4]:
arr1

array([8, 8, 3, 7], dtype=int32)

In [5]:
arr2

array([[7, 0, 4, 2],
       [5, 2, 2, 2],
       [1, 0, 8, 4]], dtype=int32)

In [7]:
sr = pd.Series(arr1)

df = pd.DataFrame(arr2, columns=['A', 'B', 'C', 'D'])

print("Series gốc:\n", sr)
print("\nDataFrame gốc:\n", df)


Series gốc:
 0    8
1    8
2    3
3    7
dtype: int32

DataFrame gốc:
    A  B  C  D
0  7  0  4  2
1  5  2  2  2
2  1  0  8  4


In [8]:
print("\nSerries sau np.exp:\n", np.exp(sr))
print("\nDataFrame sau np.sin:\n", np.sin(df))


Serries sau np.exp:
 0    2980.957987
1    2980.957987
2      20.085537
3    1096.633158
dtype: float64

DataFrame sau np.sin:
           A         B         C         D
0  0.656987  0.000000 -0.756802  0.909297
1 -0.958924  0.909297  0.909297  0.909297
2  0.841471  0.000000  0.989358 -0.756802


In [9]:
sr_simple =pd.Series([1, 2, 3], index=['a', 'b', 'c'])

print("Series gốc:\n", sr_simple)
print("\nSerries sau np.sqrt:\n", np.sqrt(sr_simple))


Series gốc:
 a    1
b    2
c    3
dtype: int64

Serries sau np.sqrt:
 a    1.000000
b    1.414214
c    1.732051
dtype: float64


In [10]:
import pandas as pd
import numpy as np
s1=pd.Series([2,4,6], index=['a', 'b', 'c'])
s2=pd.Series([1,3,5], index=['b', 'c', 'd'])


In [11]:
s1

a    2
b    4
c    6
dtype: int64

In [12]:
s2

b    1
c    3
d    5
dtype: int64

In [13]:
s3=pd.Series([2,4,6], index=['a', 'b', 'c'])
s4=pd.Series([1,3,5], index=['b', 'c', 'd'])


In [14]:
s3

a    2
b    4
c    6
dtype: int64

In [15]:
s4

b    1
c    3
d    5
dtype: int64

In [16]:
s3.add(s4, fill_value=0)

a    2.0
b    5.0
c    9.0
d    5.0
dtype: float64

In [18]:
population = pd.Series({'TP.Hồ Chí Minh':8993082,
                        'Hà Nội':830000,
                        'Thanh Hóa':3720000,
                        'Nghệ An':341000,
                        'Đồng Nai':3097107})
area = pd.Series({'Nghệ An':16493.8,
                  'Gia Lai':15336.9,
                  'Sơn La':14174.4,
                  'Đắk Lắk':13030.5,
                  'Thanh Hóa':11132.2})
print("Top 5 tỉnh/thành đông dân nhất việt nam 2023:\n",population)
print("Top 5 tỉnh/thành diện tích lớn nhất việt nam 2023:\n", area)

Top 5 tỉnh/thành đông dân nhất việt nam 2023:
 TP.Hồ Chí Minh    8993082
Hà Nội             830000
Thanh Hóa         3720000
Nghệ An            341000
Đồng Nai          3097107
dtype: int64
Top 5 tỉnh/thành diện tích lớn nhất việt nam 2023:
 Nghệ An      16493.8
Gia Lai      15336.9
Sơn La       14174.4
Đắk Lắk      13030.5
Thanh Hóa    11132.2
dtype: float64


In [19]:
density = area[:5]/population[:5]
print("Mật độ dân số tỉnh/thành :\n", density)

Mật độ dân số tỉnh/thành :
 Gia Lai                NaN
Hà Nội                 NaN
Nghệ An           0.048369
Sơn La                 NaN
TP.Hồ Chí Minh         NaN
Thanh Hóa         0.002993
Đắk Lắk                NaN
Đồng Nai               NaN
dtype: float64


In [23]:
import pandas as pd
import numpy as np
Adf=pd.DataFrame(np.random.randint(0,10(2,2)), columns=['A','B'])
Bdf=pd.DataFrame(np.random.randint(0,10(3,3)),columns=['B','A','C'])
print("Adf:\n",Adf)
print("Bdf:\n",Bdf)

<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:4: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:4: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\BICH\AppData\Local\Temp\ipykernel_22368\1077418336.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  Adf=pd.DataFrame(np.random.randint(0,10(2,2)), columns=['A','B'])


TypeError: 'int' object is not callable

In [24]:
np.random.seed(0)

arr = np.random.randint(10,size=(3,4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [25]:
arr[0]

array([5, 0, 3, 3], dtype=int32)

In [26]:
arr-arr[0]

array([[ 0,  0,  0,  0],
       [ 2,  9,  0,  2],
       [-3,  4,  4,  3]], dtype=int32)

In [27]:
df = pd.DataFrame(arr,columns=['P','Q','M','N'])
print("df:\n",df)

df:
    P  Q  M  N
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6


In [28]:
df.iloc[0]

P    5
Q    0
M    3
N    3
Name: 0, dtype: int32

In [29]:
df.iloc[0].index

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [30]:
df.columns

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [32]:
df.iloc[0].index==df.columns

array([ True,  True,  True,  True])

In [33]:
df.iloc[0].name

0

In [34]:
df

P  Q  M  N
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6

In [35]:
df-df.iloc[0]

P  Q  M  N
0  0  0  0  0
1  2  9  0  2
2 -3  4  4  3

In [36]:
df

P  Q  M  N
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6

In [37]:
df['Q']

0    0
1    9
2    4
Name: Q, dtype: int32

In [38]:
print('df1:\n', df.subtract(df['Q'], axis=0))

df1:
    P  Q  M  N
0  5  0  3  3
1 -2  0 -6 -4
2 -2  0  3  2


In [39]:
print('df2:\n', df.multiply(df['N'], axis=0))

df2:
     P   Q   M   N
0  15   0   9   9
1  35  45  15  25
2  12  24  42  36


In [40]:
import numpy as np
import pandas as pd

arr_none = np.array([1, 2, None, 3])
print("1. mảng có None (dtype=object):")
print(arr_none)

1. mảng có None (dtype=object):
[1 2 None 3]


In [41]:
type(arr_none)

numpy.ndarray

In [42]:
print("\n2. Lỗi khi tính mean() trên mảng object chứa None:")
try:
    arr_none.mean()
except TypeError as e:
    print(f"-> Lỗi: {e}")


2. Lỗi khi tính mean() trên mảng object chứa None:
-> Lỗi: unsupported operand type(s) for +: 'int' and 'NoneType'


In [ ]:
print("\n3. Minh họa lỗi khi tính sum() trên mảng object thuần:")
arr_pure_obj = np.array[1, 2, 3, '4']

In [43]:
for dtype in ['object', 'int']:
    print("dtype=",dtype)
    %timeit np.arange(1E6,dtype=dtype).sum()
    print()

dtype= object
64 ms ± 9.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype= int
1.1 ms ± 142 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)



In [44]:
arr_nan = np.array([1, np.nan, 3, 4])
print(f"Mảng gốc: {arr_nan}")

Mảng gốc: [ 1. nan  3.  4.]


In [45]:
arr_nan.sum(), arr_nan.min(), arr_nan.max()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [46]:
np.nansum(arr_nan), np.nanmin(arr_nan), np.nanmax(arr_nan)

(np.float64(8.0), np.float64(1.0), np.float64(4.0))

In [47]:
import pandas as pd
sr_auto=pd.Series([1,2, np.nan, 4, None])
sr_auto

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [48]:
sr_auto = pd.Series([1, 2, np.nan, 4, None])
print(f"Series có None và NaN: \n{sr_auto}")

Series có None và NaN: 
0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64


In [49]:
print(f"Dtype sau chuyển đổi: {sr_auto.dtype}")

Dtype sau chuyển đổi: float64


In [50]:
sr_int_na = pd.Series([1, 2, None, 4], dtype=pd.Int64Dtype())
print(f"Series giữ Int: \n{sr_int_na}")
print(f"Dtype sau: {sr_int_na.dtype}")

Series giữ Int: 
0       1
1       2
2    <NA>
3       4
dtype: Int64
Dtype sau: Int64


In [51]:
st_sr = pd.Series(['Uneti',"Khưd", None, np.nan])
st_sr

0    Uneti
1     Khưd
2     None
3      NaN
dtype: object

In [52]:
print("___ 6. Chuẩn bị DataFrame cho Demo ___")
data = {'A': [1.0, 2.0, np.nan, 4.0],
        'B': [np.nan, 6.0, 7.0, 8.0],
        'C': [9, 10, 11, 12]}
df_demo = pd.DataFrame(data)
print(f"DataFrame gốc (df_demo): \n{df_demo}")

___ 6. Chuẩn bị DataFrame cho Demo ___
DataFrame gốc (df_demo): 
     A    B   C
0  1.0  NaN   9
1  2.0  6.0  10
2  NaN  7.0  11
3  4.0  8.0  12


In [67]:
print("\n___ 7. Demo isnull() và lọc ___")
mask_na = df.isnull()
print(f"Kết quả isnull(): \n{mask_na}")


___ 7. Demo isnull() và lọc ___
Kết quả isnull(): 
       P      Q      M      N
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False


In [61]:
print("___ 8. Demo dropna(how='all') trên DataFrame ___")
df_all_na_col = df.copy()

___ 8. Demo dropna(how='all') trên DataFrame ___


In [64]:
df_all_na_col

P  Q  M  N
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6

In [66]:
df_all_na_col['D'] = np.nan
df_all_na_col['E'] = [5, 6, np.nan, 8]
print(f"DataFrame có cột D toàn NA: \n{df_all_na_col}")

ValueError: Length of values (4) does not match length of index (3)

In [65]:
df_xoa_cot = df_all_na_col.dropna(axis='columns', how='all')
print(f"\n Kết quả dropna(axis='columsn), how='all")


 Kết quả dropna(axis='columsn), how='all


In [68]:
data = pd.Series([1, np.nan, 2, None,3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [69]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [70]:
data.fillna('Không rõ')

a         1.0
b    Không rõ
c         2.0
d    Không rõ
e         3.0
dtype: object

In [71]:
df_demo

A    B   C
0  1.0  NaN   9
1  2.0  6.0  10
2  NaN  7.0  11
3  4.0  8.0  12

In [72]:
df_filled = df_demo.fillna(0)
df_filled

A    B   C
0  1.0  0.0   9
1  2.0  6.0  10
2  0.0  7.0  11
3  4.0  8.0  12

In [73]:
df_demo

A    B   C
0  1.0  NaN   9
1  2.0  6.0  10
2  NaN  7.0  11
3  4.0  8.0  12

In [74]:
print("___9. Demo fillna() bảng giá trị thống kê___")
print(f"DataFrame gốc: \n{df_demo}")
mean_A = df_demo['A'].mean()
df_fill_mean = df_demo.fillna({'A': mean_A})
print(f"giá trị trung bình của cột A là: {mean_A:.2f}")
print(f"kết quả fillna bảngn mean của A là: \n{df_fill_mean}")

___9. Demo fillna() bảng giá trị thống kê___
DataFrame gốc: 
     A    B   C
0  1.0  NaN   9
1  2.0  6.0  10
2  NaN  7.0  11
3  4.0  8.0  12
giá trị trung bình của cột A là: 2.33
kết quả fillna bảngn mean của A là: 
          A    B   C
0  1.000000  NaN   9
1  2.000000  6.0  10
2  2.333333  7.0  11
3  4.000000  8.0  12


In [91]:
import pandas as pd
index_tuples = [
                ('Hà Nội', 2015), ('Hà Nội', 2020),
                ('Nam Định', 2015), ('Nam Định', 2020),
                ('Thanh Hóa', 2015), ('Thanh Hóa', 2020),
                ('Đà Nẵng', 2015), ('Đà Nẵng', 2020),
                ('Hồ Chí Minh', 2015), ('Hồ Chí Minhh', 2020)]
data = [ 7216000, 8246540,
        1850600, 1780330,
        3514200, 3664940,
        1028800, 1169480,
        8146300, 9227600]


In [92]:
vn_pop = pd.Series(data, index=index_tuples)

print("Series sử dụng Index bằng Tuple ( cách thủ công):")
vn_pop

Series sử dụng Index bằng Tuple ( cách thủ công):


(Hà Nội, 2015)          7216000
(Hà Nội, 2020)          8246540
(Nam Định, 2015)        1850600
(Nam Định, 2020)        1780330
(Thanh Hóa, 2015)       3514200
(Thanh Hóa, 2020)       3664940
(Đà Nẵng, 2015)         1028800
(Đà Nẵng, 2020)         1169480
(Hồ Chí Minh, 2015)     8146300
(Hồ Chí Minhh, 2020)    9227600
dtype: int64

In [94]:
vn_pop[('Hà Nội', 2015):('Nam Định',2015)]


(Hà Nội, 2015)      7216000
(Hà Nội, 2020)      8246540
(Nam Định, 2015)    1850600
dtype: int64

In [95]:
vn_pop.index

Index([      ('Hà Nội', 2015),       ('Hà Nội', 2020),     ('Nam Định', 2015),
           ('Nam Định', 2020),    ('Thanh Hóa', 2015),    ('Thanh Hóa', 2020),
            ('Đà Nẵng', 2015),      ('Đà Nẵng', 2020),  ('Hồ Chí Minh', 2015),
       ('Hồ Chí Minhh', 2020)],
      dtype='object')

In [ ]:
#lọc các hàng có năm là 2020
vn_pop[[i for i in vn_pop.index if i[1]==2020]]


(Hà Nội, 2020)          8246540
(Nam Định, 2020)        1780330
(Thanh Hóa, 2020)       3664940
(Đà Nẵng, 2020)         1169480
(Hồ Chí Minhh, 2020)    9227600
dtype: int64

In [98]:
multi_idx = pd.MultiIndex.from_tuples(index_tuples, name=['Tỉnh/TP', 'Năm'])
multi_idx

MultiIndex([(      'Hà Nội', 2015),
            (      'Hà Nội', 2020),
            (    'Nam Định', 2015),
            (    'Nam Định', 2020),
            (   'Thanh Hóa', 2015),
            (   'Thanh Hóa', 2020),
            (     'Đà Nẵng', 2015),
            (     'Đà Nẵng', 2020),
            ( 'Hồ Chí Minh', 2015),
            ('Hồ Chí Minhh', 2020)],
           names=['Tỉnh/TP', 'Năm'])

In [99]:
vn_pop_mul = vn_pop.reindex(multi_idx)
vn_pop_mul

Tỉnh/TP       Năm 
Hà Nội        2015    7216000
              2020    8246540
Nam Định      2015    1850600
              2020    1780330
Thanh Hóa     2015    3514200
              2020    3664940
Đà Nẵng       2015    1028800
              2020    1169480
Hồ Chí Minh   2015    8146300
Hồ Chí Minhh  2020    9227600
dtype: int64

In [100]:
type(vn_pop_mul)

pandas.core.series.Series

In [101]:
vn_pop_mul[:, 2020]

Tỉnh/TP
Hà Nội          8246540
Nam Định        1780330
Thanh Hóa       3664940
Đà Nẵng         1169480
Hồ Chí Minhh    9227600
dtype: int64

In [102]:
vn_pop_mul

Tỉnh/TP       Năm 
Hà Nội        2015    7216000
              2020    8246540
Nam Định      2015    1850600
              2020    1780330
Thanh Hóa     2015    3514200
              2020    3664940
Đà Nẵng       2015    1028800
              2020    1169480
Hồ Chí Minh   2015    8146300
Hồ Chí Minhh  2020    9227600
dtype: int64

In [104]:
vn_pop_df = vn_pop_mul.unstack('Năm')
print("Dataframe dạng rộng ( cột là Năm ):")
display(vn_pop_df)

print("\nSeries dạng dài (stack lại):")
display(vn_pop_df.stack())

Dataframe dạng rộng ( cột là Năm ):


Năm                2015       2020
Tỉnh/TP                           
Hà Nội        7216000.0  8246540.0
Hồ Chí Minh   8146300.0        NaN
Hồ Chí Minhh        NaN  9227600.0
Nam Định      1850600.0  1780330.0
Thanh Hóa     3514200.0  3664940.0
Đà Nẵng       1028800.0  1169480.0


Series dạng dài (stack lại):


Tỉnh/TP       Năm 
Hà Nội        2015    7216000.0
              2020    8246540.0
Hồ Chí Minh   2015    8146300.0
Hồ Chí Minhh  2020    9227600.0
Nam Định      2015    1850600.0
              2020    1780330.0
Thanh Hóa     2015    3514200.0
              2020    3664940.0
Đà Nẵng       2015    1028800.0
              2020    1169480.0
dtype: float64

In [106]:
type(vn_pop_df)

pandas.core.frame.DataFrame

In [107]:
type(vn_pop_df.stack())

pandas.core.series.Series

In [108]:
vn_pop_df.stack()

Tỉnh/TP       Năm 
Hà Nội        2015    7216000.0
              2020    8246540.0
Hồ Chí Minh   2015    8146300.0
Hồ Chí Minhh  2020    9227600.0
Nam Định      2015    1850600.0
              2020    1780330.0
Thanh Hóa     2015    3514200.0
              2020    3664940.0
Đà Nẵng       2015    1028800.0
              2020    1169480.0
dtype: float64

In [ ]:
vn_pop_df

Năm                2015       2020
Tỉnh/TP                           
Hà Nội        7216000.0  8246540.0
Hồ Chí Minh   8146300.0        NaN
Hồ Chí Minhh        NaN  9227600.0
Nam Định      1850600.0  1780330.0
Thanh Hóa     3514200.0  3664940.0
Đà Nẵng       1028800.0  1169480.0

: 

In [1]:
co_viec_2015 = [375320, 1080750, 1512340, 4920000]
co_viec_2020 = [ 4042456, 1011049, 1600000, 5200000]

vn_pop_df_expanded = pd.DataFrame({
    ('Tổng dân số', 2015): vn_pop_df[2015],
    ('tổng dân số', 2020): vn_pop_df[2020],
    ('có việc', 2015): co_viec_2015,
    ('có việc', 2020): co_viec_2020,
}, index=vn_pop_df.index)

vn_pop_df_expanded.columns = pd.MultiIndex.from_tuples(vn_pop_df_expanded.columns, name=['Chỉ tiêu', 'Năm'])

vn_pop_df_expanded

NameError: name 'pd' is not defined

In [ ]:
idx_arr = [['a','a','b','b'], [1,2,1,2]]
data=np.random.rand(4,3)

multi_index=pd.MultiIndex.from_arrays(idx_arr,names = ['Data1','Data2'])
df=pd.DataFrame(data,index)

In [9]:
import pandas as pd
import numpy as np
index=pd.MultiIndex.from_product([[2020,2021,2022],[1,2,3]],
                                 names=['Năm', 'Lần thi'])
columns=pd.MultiIndex.from_product([['Bình','Lan','Vân'],
                                    ['Toán','Lý','Hóa']],
                                    names=['Học sinh','Môn học'])
data=np.random.randint(5,10,(9,9))
'''Tạo DataFrame score'''
score=pd.DataFrame(data,index=index, columns=columns)
score

Học sinh     Bình         Lan         Vân       
Môn học      Toán Lý Hóa Toán Lý Hóa Toán Lý Hóa
Năm  Lần thi                                    
2020 1          5  5   8    5  6   6    7  5   5
     2          5  5   8    6  5   8    5  9   7
     3          7  5   9    5  9   7    5  6   9
2021 1          6  8   6    7  6   5    6  5   9
     2          9  5   5    9  6   9    9  5   7
     3          7  8   8    6  7   6    7  5   7
2022 1          7  7   6    9  5   8    6  7   7
     2          6  8   5    9  8   5    9  6   5
     3          6  7   7    5  8   5    7  5   7